// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/news": {
    params: {};
  };
  "/news/:id": {
    params: {
      "id": string;
    };
  };
  "/create-news-post": {
    params: {};
  };
  "/eugenics": {
    params: {};
  };
  "/create-eugenics-article": {
    params: {};
  };
  "/lawsuit": {
    params: {};
  };
  "/lawsuit/documents": {
    params: {};
  };
  "/main": {
    params: {};
  };
  "/petition": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/auth" | "/news" | "/news/:id" | "/create-news-post" | "/eugenics" | "/create-eugenics-article" | "/lawsuit" | "/lawsuit/documents" | "/main" | "/petition";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/news.tsx": {
    id: "routes/news";
    page: "/news";
  };
  "routes/news-post.tsx": {
    id: "routes/news-post";
    page: "/news/:id";
  };
  "routes/create-news-post.tsx": {
    id: "routes/create-news-post";
    page: "/create-news-post";
  };
  "routes/eugenics.tsx": {
    id: "routes/eugenics";
    page: "/eugenics";
  };
  "routes/create-eugenics-article.tsx": {
    id: "routes/create-eugenics-article";
    page: "/create-eugenics-article";
  };
  "routes/lawsuit.tsx": {
    id: "routes/lawsuit";
    page: "/lawsuit";
  };
  "routes/documents.tsx": {
    id: "routes/documents";
    page: "/lawsuit/documents";
  };
  "routes/main.tsx": {
    id: "routes/main";
    page: "/main";
  };
  "routes/petition.tsx": {
    id: "routes/petition";
    page: "/petition";
  };
};