// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/create-blog-post": {
    params: {};
  };
  "/lawsuit": {
    params: {};
  };
  "/lawsuit/documents": {
    params: {};
  };
  "/main": {
    params: {};
  };
  "/petition": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/auth" | "/blog" | "/blog/:id" | "/create-blog-post" | "/lawsuit" | "/lawsuit/documents" | "/main" | "/petition";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blog-post.tsx": {
    id: "routes/blog-post";
    page: "/blog/:id";
  };
  "routes/create-blog-post.tsx": {
    id: "routes/create-blog-post";
    page: "/create-blog-post";
  };
  "routes/lawsuit.tsx": {
    id: "routes/lawsuit";
    page: "/lawsuit";
  };
  "routes/documents.tsx": {
    id: "routes/documents";
    page: "/lawsuit/documents";
  };
  "routes/main.tsx": {
    id: "routes/main";
    page: "/main";
  };
  "routes/petition.tsx": {
    id: "routes/petition";
    page: "/petition";
  };
};